### ISSUE TITLE
Agregar uno o varios campos de imágenes

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#11]
(aunque sea un thumbnail)

**Comment by matiasiglesias** [comment]
@Pazitos10 esto decís para las empresas locales no?

**Comment by Pazitos10** [comment]
@matiasiglesias , sip. Me refería al form de alta de empresas. junto con el/los campos de imágenes. Para que en el listado cuando el usuario busca y selecciona, la empresa tenga algunas imágenes para mostrar. Mínimo un thumbnail para el listado y otra mas para la parte de detalles.
