### ISSUE TITLE
Agregar campos para horarios

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#12]
Para empresas locales

**Comment by Pazitos10** [comment]
Resumen tl;dr del commit:

Formulario de creación/edición de empresas. Se añadió el siguiente campo:
![captura de pantalla de 2017-02-05 20-21-00](https://cloud.githubusercontent.com/assets/5199304/22635286/066b74f2-ec11-11e6-94a2-33aba6543d1a.png)

En la parte superior figura el día de la semana, debajo los horarios de atención a completar por el usuario. Se asume que como máximo habrán 2 turnos. Para cambiar el día se utilizan las flechas ubicadas en la parte superior izquierda (navegar los días para atrás) y derecha (navegar los días para adelante).
Angular se encarga de mantener el estado de los datos a medida que se van cargando.

Se guardan exitosamente en el servidor y no hay problemas para mostrar ni editar los valores nuevamente.

Editando:

![captura de pantalla de 2017-02-06 02-13-32](https://cloud.githubusercontent.com/assets/5199304/22635385/0267cb5c-ec12-11e6-99a3-4a73df616a52.png)

![captura de pantalla de 2017-02-06 02-13-47](https://cloud.githubusercontent.com/assets/5199304/22635386/03e0649e-ec12-11e6-961d-cd394bf97489.png)


Listando:

![captura de pantalla de 2017-02-06 02-19-02](https://cloud.githubusercontent.com/assets/5199304/22635451/ac7959c6-ec12-11e6-94ff-2af4d450c95d.png)

![captura de pantalla de 2017-02-06 01-49-02](https://cloud.githubusercontent.com/assets/5199304/22635390/0bafb436-ec12-11e6-809c-62b142ddfba6.png)

![captura de pantalla de 2017-02-06 02-15-30](https://cloud.githubusercontent.com/assets/5199304/22635399/2c539694-ec12-11e6-9828-40765749eb15.png)

Al mismo tiempo, se corrigieron algunos bugs del listado relacionados a inconsistencias entre estructuras de datos, el template estaba muy acoplado a la estructura de datos de google places. 
Ahora se puede mostrar sin problemas si un lugar se encuentra abierto o cerrado sin tener en cuenta si se trata de una empresa local o de un google place. Situación que se refleja en los detalles del sitio como puede verse en capturas superiores.

Siendo las 02:25 am, dejo la guardia. [10-7](https://es.wikipedia.org/wiki/C%C3%B3digos_10#10-0), cambio y fuera.(?

**Comment by matiasiglesias** [comment]
@Pazitos10 No me funciona.. :-(
Hice `npm install` y me instaló estos paquetes:
```
angular-moment#1.0.1 public/lib/angular-moment
├── angular#1.3.20
└── moment#2.17.1

ng-file-upload#12.2.13 public/lib/ng-file-upload
└── angular#1.3.20

moment#2.17.1 public/lib/moment
```
Pero al entrar en la pantalla me da un error feo de consola. Ver #24

**Comment by Pazitos10** [comment]
Fue resuelto en [dbbd586](https://github.com/Pazitos10/AplicacionesWeb/commit/dbbd586c4d31d37fc773b399eda5f88ab9650729)
