### ISSUE TITLE
Adaptar listado de Empresas

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#14]
Eliminar el listado convencional de empresas o bien adaptarlo para que solo muestre las favoritas y las creadas por uno mismo o algo así.
@Pazitos10 podriamos poner un filtro para que por defecto solo muestre las favoritas

**Comment by Pazitos10** [comment]
@matiasiglesias Excelente!

**Comment by matiasiglesias** [comment]
Agregado filtro de solo empresas likeadas
Agregado filtro de empresas por texto

Ver 24c3ecb329c35730d21658d81075e3897c52f4ef
