### ISSUE TITLE
Búsqueda no trae resultados

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#16]

**Comment by matiasiglesias** [comment]
<img width="1301" alt="captura de pantalla 2017-02-01 a las 08 44 38" src="https://cloud.githubusercontent.com/assets/2591889/22505531/bae49a68-e85a-11e6-996e-f24b3368cd7a.png">
Probablemente sea algún cambio en el modelo

**Comment by Pazitos10** [comment]
@matiasiglesias:

1. ¿Si buscas sin parámetros (nombre) trae resultados?
2. ¿La empresa que buscas es de google places o local (creada por vos)?
