### ISSUE TITLE
Mostrar ubicación de empresas locales

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#18]
En la vista de empresas, mostrar el mapa con la ubicación, como se hace en el alta y edición que detecta la ubicación

**Comment by Pazitos10** [comment]
@matiasiglesias, esto es en el listado de empresas? o cuando haces clic en una (que muestra el detalle)?

**Comment by matiasiglesias** [comment]
Se muestra mapa a la derecha de la información
ver a941cce9e53394b3e4a1445d9cbd9b9c22d81d1e
