### ISSUE TITLE
Error en creación de empresa

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#23]
![captura de pantalla 2017-02-06 a las 08 30 50](https://cloud.githubusercontent.com/assets/2591889/22645622/a89cf838-ec46-11e6-80a3-58f408fa6284.png)

**Comment by Pazitos10** [comment]
Pude reproducir el error, se debía a la siguiente modificación:

```javascript
    if (vm.empresa === null) {
      obtenerUbicacion();
    } else {
      var position = { coords: { latitude: vm.empresa.location[0], longitude: vm.empresa.location[1] } };
      initMap(position);
      createMarker({ lat: vm.empresa.location[0], lng:  vm.empresa.location[1] });
    }
```

Donde debido al merge, vm.empresa es inicializado con anterioridad (se inicializa el atributo opening_hours) y al momento de ejecutar estas lineas ya es distinto de null, pero no tiene el atributo location. 
Fue resuelto en  [dbbd586](https://github.com/Pazitos10/AplicacionesWeb/commit/dbbd586c4d31d37fc773b399eda5f88ab9650729)

**Comment by matiasiglesias** [comment]
jajaja. Mala mía entonces! ;-)
