### ISSUE TITLE
Guardar empresa localmente

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#6]
@Pazitos10 te parece implementar algo así? Los resultados que trae de google places mostrarlos con el favorito sin relleno y los que están localmente con el favorito con relleno? De esa manera, al hacer click sobre un lugar de google places se guardaría localmente
@Pazitos10 otra opción sería poner un pin clavado para los que están guardados localmente
![captura de pantalla 2017-01-29 a las 14 27 13](https://cloud.githubusercontent.com/assets/2591889/22406314/f193e80c-e62f-11e6-886f-ce0eebe2ba3f.png)

**Comment by matiasiglesias** [comment]
Si, igual vamos a tener que compatibilizar las estructuras para traer en las búsquedas los datos locales y mostrarlos primero....

**Comment by Pazitos10** [comment]
@matiasiglesias exacto!
