### ISSUE TITLE
Deshabilitar login sociales

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#7]
Deshabilitar los que no se usan o los que tienen problemas

**Comment by matiasiglesias** [comment]
Paypal solo permite a cuentas business radicadas en AU, CA, GB, FR, IT, SG, JP, DE, US, IN, C2, HK. Se deshabilita

**Comment by Pazitos10** [comment]
Perfecto!

**Comment by matiasiglesias** [comment]
No puedo hacer andar Google. Después del login me redirecciona a http://localhost:3000/authentication/signin?err=# y no me da mayor detalle. Lo deshabilito

**Comment by matiasiglesias** [comment]
Se corrigió un problema del framework con los callback del OAuth que forzaba a recargar la página varias veces hasta que tome el login
Se eliminó login con Google y Paypal

Ver 2ab965e2e62f828a1c1a0fa08909cd447feb0a41
