### ISSUE TITLE
Listado de empresas locales

### ISSUE THREAD

**Issue by matiasiglesias** [Pazitos10/AplicacionesWeb#9]
Arreglar columnas para aquellas empresas que no tienen cargado teléfono
<img width="1440" alt="captura de pantalla 2017-02-01 a las 08 37 11" src="https://cloud.githubusercontent.com/assets/2591889/22505323/ae5fb44a-e859-11e6-8d51-27e3c8c994e1.png">

**Comment by Pazitos10** [comment]
@matiasiglesias, podemos corregirlo desde el template nomas:

```html
   <span ng-if="empresa.telefono.length > 0" class="col-md-4">
       <i class="material-icons md-14">call</i> <span ng-bind="empresa.telefono"></span>
   </span>
   <span ng-if="!empresa.telefono.length > 0" class="col-md-4">
       <i class="material-icons md-14">call</i> <span> No disponible </span>
   </span>
```

![captura de pantalla de 2017-02-01 14-35-10](https://cloud.githubusercontent.com/assets/5199304/22518552/c6a14280-e88b-11e6-9d21-afdce78a0b77.png)

**Comment by matiasiglesias** [comment]
Ver 6e2e9c97b8a87a121d59abdeb43537daade92223
